/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.ProdutoController;
import Model.Produto;
import Model.Validacao;
import javax.swing.JOptionPane;

/**
 *
 * @author anibal
 */
public class CadastroAlteracaoProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroEAlteracaoProduto
     */
    public CadastroAlteracaoProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbtipo = new javax.swing.JComboBox<>();
        txtQuantidade = new javax.swing.JFormattedTextField();
        txtCusto = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();

        jLabel1.setText("Nome Do Produto");

        jLabel2.setText("Tipo");

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "alimentos não perecíveis" }));

        txtQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtQuantidade.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        txtQuantidade.setMinimumSize(new java.awt.Dimension(4, 22));
        txtQuantidade.setPreferredSize(new java.awt.Dimension(4, 22));

        txtCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCusto.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        txtCusto.setMinimumSize(new java.awt.Dimension(4, 22));
        txtCusto.setPreferredSize(new java.awt.Dimension(4, 22));

        jLabel3.setText("Quantidade");

        jLabel4.setText("MT");

        jLabel5.setText("MT");

        jLabel6.setText("Valor");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jLabel7.setText("Descrição");

        btnCadastrar.setBackground(new java.awt.Color(0, 153, 255));
        btnCadastrar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar Produto");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel8.setText("Custo");

        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValor.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        txtValor.setMinimumSize(new java.awt.Dimension(4, 22));
        txtValor.setPreferredSize(new java.awt.Dimension(4, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(662, 662, 662)
                        .addComponent(btnCadastrar)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
         //validacao dos campos se foram preenchidos
        String produtoPreenchido = Validacao.ProdutoCamposVazios(txtNome.getText(),
            txtQuantidade.getText(), txtCusto.getText(), txtValor.getText());
        
        //Se os campos obrigatórios estiverem okay
        if (produtoPreenchido.equalsIgnoreCase("") || produtoPreenchido == "")
        {
            
            //valida se os campos foram preenchidos com o tamanho correto
            String produtoTamanhoOK = Validacao.ProdutoCamposTamanho(txtNome.getText(),
            txtQuantidade.getText(), txtCusto.getText(), txtValor.getText());
            
            //Se os campos forem preenchidos com o tamanho correto
            if (produtoTamanhoOK.equalsIgnoreCase("") || produtoTamanhoOK == "")
            {
            
                String respostaController = null;

                //verifica se nao esta em modo de edicao
                if (!modoEdicao){
                    //caso nao esteja cria um novo objeto
                    produto = new Produto();
                }

                //coloca dados nos atributos (instancia ocorre no inicio da classe)
                produto.setNome(txtNome.getText());
                produto.setCategoria(cbtipo.getSelectedItem().toString());
                produto.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
                produto.setCusto(Float.parseFloat(txtCusto.getText().replaceAll(",", ".")));
                produto.setValor(Float.parseFloat(txtValor.getText().replaceAll(",", ".")));
                produto.setDescricao(txtDescricao.getText());

                if (!modoEdicao)//for modo de cadastro
                {
                    //envia produto para salvar para o controller
                    respostaController = ProdutoController.salvar(produto);
                }
                else//caso for mode de alteracao
                {
                    respostaController = ProdutoController.atualizar(produto);
                }

                //verifica resposta do controller
                if (respostaController == null)//se a resposta for positiva
                {
                    if (!modoEdicao)//se for modo de cadastro
                    {
                        JOptionPane.showMessageDialog(rootPane,
                            "Produto cadastrado com sucesso!",
                            "Confirmação",
                            JOptionPane.INFORMATION_MESSAGE);
                    } 
                    else//caso for modo de alteracao
                    {
                        JOptionPane.showMessageDialog(rootPane,
                            "Produto atualizado com sucesso!",
                            "Confirmação",
                            JOptionPane.INFORMATION_MESSAGE);    
                        this.dispose();
                    }
                    //Limpa o formulário
                    limparFormulario();
                }
                else//se a resposta do controller for negativa
                {
                    //Exibe mensagens de erro para o usuário
                    JOptionPane.showMessageDialog(rootPane, 
                            respostaController
                                +"\n Procure o administrador do sistema!",
                            "Erro", 
                            JOptionPane.ERROR_MESSAGE);
                }
            }
            else//se os campos foram preenchidos com tamanhos incorretos 
            {
                JOptionPane.showMessageDialog(rootPane, 
                    "Os campos abaixo ultrapassaram os limites de caracteres:" 
                            + produtoTamanhoOK + 
                            "\nPreencha os campo corretamente e tente novamente!",
                    "Erro", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
        else//se os campos obrigatorios nao foram preenchidos
        {
            JOptionPane.showMessageDialog(this,"O(s) campo(s) abaixo:\n"+produtoPreenchido+
                "Não foram preenchidos, preencha-os e tente novamente!");
        }
      
    }//GEN-LAST:event_btnCadastrarActionPerformed


    
    //INSTANCIA DE PRODUTO PARA CASO DE EDICAO
    private Produto produto = null;
    
    //MODO DA TELA CRIAÇÃO E EDICAO
    private boolean modoEdicao = false;
    
    //ID DE PRODUTO PARA CASO DE EDICAO
    private Integer idProduto;

    //Get e set das Declaracoes
    public Produto getProduto() {
        return produto;
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    public boolean isModoEdicao() {
        return modoEdicao;
    }

    public void setModoEdicao(boolean modoEdicao) {
        this.modoEdicao = modoEdicao;
    }

    public Integer getIdProduto() {
        return idProduto;
    }

    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    
    // Limpar Formulario 
     public void limparFormulario(){
        txtNome.setText("");
        cbtipo.setSelectedIndex(0); 
        txtQuantidade.setText("");
        txtCusto.setText("");
        txtValor.setText("");
        txtDescricao.setText("");
    }
      //CARREGA DADOS DO PRODUTO
    public void carregarDadosTela(){
        //verifica se está no modo de edição e há um produto para edição
        if (modoEdicao && produto != null) 
        {
            txtNome.setText(produto.getNome());
            
            //combobox fazer for e achar item 
            for (int i = 0; i < cbtipo.getItemCount(); i++) 
            {
                if (cbtipo.getItemAt(i).equals(produto.getCategoria())) 
                {
                    cbtipo.setSelectedIndex(i);
                    break;
                }
            }
            
            //campos formatados usar "setValue"
            txtQuantidade.setValue(produto.getQuantidade());
            txtCusto.setValue(produto.getCusto());
            txtValor.setValue(produto.getValor());
            
            txtDescricao.setText(produto.getDescricao());
        }
    }
     
     
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtCusto;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtQuantidade;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
