/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author anibal
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuAdmin() {
        initComponents();
    }

    public MenuAdmin(String user) {
        initComponents();
        txtuser.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jbCabcalho = new javax.swing.JPanel();
        txtuser = new javax.swing.JLabel();
        Sair = new javax.swing.JLabel();
        jpMenu = new javax.swing.JPanel();
        Menu = new javax.swing.JLabel();
        jpRelatorios = new javax.swing.JPanel();
        txtRelatrios = new javax.swing.JLabel();
        jpCadastroProduto = new javax.swing.JPanel();
        txtCadastroProduto = new javax.swing.JLabel();
        jpConsultaProduto = new javax.swing.JPanel();
        txtConsultaProduto = new javax.swing.JLabel();
        jpConsultarUsuarios = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        PainelPrincipal = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbCabcalho.setBackground(new java.awt.Color(255, 153, 0));

        txtuser.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setText("USER");

        Sair.setBackground(new java.awt.Color(255, 255, 255));
        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jbCabcalhoLayout = new javax.swing.GroupLayout(jbCabcalho);
        jbCabcalho.setLayout(jbCabcalhoLayout);
        jbCabcalhoLayout.setHorizontalGroup(
            jbCabcalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbCabcalhoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtuser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sair)
                .addGap(34, 34, 34))
        );
        jbCabcalhoLayout.setVerticalGroup(
            jbCabcalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbCabcalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbCabcalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuser)
                    .addComponent(Sair))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jpMenu.setBackground(new java.awt.Color(255, 102, 0));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("MENU PRINCIPAL");

        jpRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpRelatoriosMousePressed(evt);
            }
        });

        txtRelatrios.setText("VENDAS REALIZADAS");
        txtRelatrios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRelatriosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRelatriosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpRelatoriosLayout = new javax.swing.GroupLayout(jpRelatorios);
        jpRelatorios.setLayout(jpRelatoriosLayout);
        jpRelatoriosLayout.setHorizontalGroup(
            jpRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRelatoriosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRelatrios)
                .addGap(61, 61, 61))
        );
        jpRelatoriosLayout.setVerticalGroup(
            jpRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRelatrios, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpCadastroProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpCadastroProdutoMousePressed(evt);
            }
        });

        txtCadastroProduto.setText("CADASTRAR PRODUTO");
        txtCadastroProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCadastroProdutoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpCadastroProdutoLayout = new javax.swing.GroupLayout(jpCadastroProduto);
        jpCadastroProduto.setLayout(jpCadastroProdutoLayout);
        jpCadastroProdutoLayout.setHorizontalGroup(
            jpCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(txtCadastroProduto)
                .addGap(46, 46, 46))
        );
        jpCadastroProdutoLayout.setVerticalGroup(
            jpCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroProdutoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtCadastroProduto)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jpConsultaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpConsultaProdutoMousePressed(evt);
            }
        });

        txtConsultaProduto.setText("ESTOQUE");
        txtConsultaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConsultaProdutoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpConsultaProdutoLayout = new javax.swing.GroupLayout(jpConsultaProduto);
        jpConsultaProduto.setLayout(jpConsultaProdutoLayout);
        jpConsultaProdutoLayout.setHorizontalGroup(
            jpConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultaProdutoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtConsultaProduto)
                .addGap(102, 102, 102))
        );
        jpConsultaProdutoLayout.setVerticalGroup(
            jpConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaProdutoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtConsultaProduto)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpConsultarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpConsultarUsuariosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpConsultarUsuariosLayout = new javax.swing.GroupLayout(jpConsultarUsuarios);
        jpConsultarUsuarios.setLayout(jpConsultarUsuariosLayout);
        jpConsultarUsuariosLayout.setHorizontalGroup(
            jpConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        jpConsultarUsuariosLayout.setVerticalGroup(
            jpConsultarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpConsultaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCadastroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpConsultarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Menu)
                .addGap(18, 18, 18)
                .addComponent(jpRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpConsultarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jpCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jpConsultaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(853, 514));

        PainelPrincipal.setPreferredSize(new java.awt.Dimension(853, 514));

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbCabcalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addComponent(jbCabcalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpCadastroProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCadastroProdutoMousePressed
        // TODO add your handling code here:
        cadastrarProduto();
       jpCadastroProduto.setBackground(Color.red);
          txtCadastroProduto.setForeground(Color.WHITE);
          
           jpConsultaProduto.setBackground(new Color(242,242,242));
          txtConsultaProduto.setForeground(Color.black);
          
            jpRelatorios.setBackground(new Color(242,242,242));
           txtRelatrios.setForeground(Color.BLACK);
          
    }//GEN-LAST:event_jpCadastroProdutoMousePressed

    private void jpConsultaProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpConsultaProdutoMousePressed
        // TODO add your handling code here:
        consultarProduto();
        jpConsultaProduto.setBackground(Color.red);
          txtConsultaProduto.setForeground(Color.WHITE);
          
          jpCadastroProduto.setBackground(new Color(242,242,242));
          txtCadastroProduto.setForeground(Color.BLACK);

            jpRelatorios.setBackground(new Color(242,242,242));
           txtRelatrios.setForeground(Color.BLACK);
           
    }//GEN-LAST:event_jpConsultaProdutoMousePressed

    private void jpRelatoriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpRelatoriosMousePressed
        // TODO add your handling code here:
        Relatorio();
          jpRelatorios.setBackground(Color.red);
          txtRelatrios.setForeground(Color.WHITE);
          
           jpConsultaProduto.setBackground(new Color(242,242,242));
          txtConsultaProduto.setForeground(Color.BLACK);
          
          jpCadastroProduto.setBackground(new Color(242,242,242));
          txtCadastroProduto.setForeground(Color.BLACK);
          
        
    }//GEN-LAST:event_jpRelatoriosMousePressed

    private void txtConsultaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsultaProdutoMouseClicked
        // TODO add your handling code here:
        consultarProduto();
         jpConsultaProduto.setBackground(Color.red);
          txtConsultaProduto.setForeground(Color.WHITE);
          
            jpRelatorios.setBackground(new Color(242,242,242));
           txtRelatrios.setForeground(Color.BLACK);
           
           jpCadastroProduto.setBackground(new Color(242,242,242));
          txtCadastroProduto.setForeground(Color.BLACK);

    }//GEN-LAST:event_txtConsultaProdutoMouseClicked

    private void txtRelatriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRelatriosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRelatriosMousePressed

    private void txtRelatriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRelatriosMouseClicked
        // TODO add your handling code here:
        Relatorio();
        jpRelatorios.setBackground(Color.red);
        txtRelatrios.setForeground(Color.WHITE);
        
         jpConsultaProduto.setBackground(new Color(242,242,242));
          txtConsultaProduto.setForeground(Color.black);
          
          jpCadastroProduto.setBackground(new Color(242,242,242));
         txtCadastroProduto.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtRelatriosMouseClicked

    private void txtCadastroProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCadastroProdutoMouseClicked
        // TODO add your handling code here:
        cadastrarProduto();
         jpCadastroProduto.setBackground(Color.red);
          txtCadastroProduto.setForeground(Color.WHITE);
          
           jpConsultaProduto.setBackground(new Color(242,242,242));
          txtConsultaProduto.setForeground(Color.black);
          
            jpRelatorios.setBackground(new Color(242,242,242));
           txtRelatrios.setForeground(Color.BLACK);
           
           
    }//GEN-LAST:event_txtCadastroProdutoMouseClicked

    private void jpConsultarUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpConsultarUsuariosMousePressed
        // TODO add your handling code here:
        //  RegistrarUsuario();
    }//GEN-LAST:event_jpConsultarUsuariosMousePressed

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        // TODO add your handling code here:
        sairDaTela();
        
    }//GEN-LAST:event_SairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    private CadastroAlteracaoProduto cap;
    private ConsultaProduto cp;
    private VendasRealizadas rv;

    public JDesktopPane getPainelPrincipal() {
        return PainelPrincipal;
    }

    public void setPainelPrincipal(JDesktopPane PainelPrincipal) {
        this.PainelPrincipal = PainelPrincipal;
    }

    //Relatorio
    public void Relatorio() {
        //verifica se a tela ja existe
        if (rv == null) {
            //se não existir faz uma tela

            rv = new VendasRealizadas();
        }

        //verifico se a tela ja esta no painel
        if (!rv.isVisible()) {
            //mostro a tela no painel principal caso nao esteja la
            PainelPrincipal.add(rv);
            rv.setVisible(true);
        }

        //coloco ela na frente de todas para todos os casos
        rv.toFront();

        //redimensiona tela para tamanho do painel
        try {
            rv.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

        //retira o painel superior
        ((BasicInternalFrameUI) rv.getUI()).setNorthPane(null);
    }

    //CADASTRAR PRODUTO
    public void cadastrarProduto() {
        //verifica se a tela ja existe
        if (cap == null) {
            //se não existir faz uma tela
            cap = new CadastroAlteracaoProduto();
        }

        //verifico se a tela ja esta no painel
        if (!cap.isVisible()) {
            PainelPrincipal.add(cap);//esta dando erro
            cap.setVisible(true);
        }

        //coloco ela na frente de todas para todos os casos
        cap.toFront();

        //redimensiona tela para tamanho do painel
        try {
            cap.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

        //retira o painel superior
        ((BasicInternalFrameUI) cap.getUI()).setNorthPane(null);
    }

    //CONSULTAR PRODUTO
    public void consultarProduto() {
        //verifica se a tela ja existe
        if (cp == null) {
            //se não existir faz uma tela

            cp = new ConsultaProduto();
        }

        //verifico se a tela ja esta no painel
        if (!cp.isVisible()) {
            //mostro a tela no painel principal caso nao esteja la
            PainelPrincipal.add(cp);//da erro
            cp.setVisible(true);
        }

        //coloco ela na frente de todas para todos os casos
        cp.toFront();

        //redimensiona tela para tamanho do painel
        try {
            cp.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

        //limpa tabela de pesquisa
        //cp.tableModelLimpar();

        //retira o painel superior
        ((BasicInternalFrameUI) cp.getUI()).setNorthPane(null);
    }

     private void sairDaTela() {
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            dispose();
        }
     }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JDesktopPane PainelPrincipal;
    private javax.swing.JLabel Sair;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jbCabcalho;
    private javax.swing.JPanel jpCadastroProduto;
    private javax.swing.JPanel jpConsultaProduto;
    private javax.swing.JPanel jpConsultarUsuarios;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpRelatorios;
    private javax.swing.JLabel txtCadastroProduto;
    private javax.swing.JLabel txtConsultaProduto;
    private javax.swing.JLabel txtRelatrios;
    private javax.swing.JLabel txtuser;
    // End of variables declaration//GEN-END:variables
}
